version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_PYTHON_PII_ENDPOINT=http://localhost:8000
    networks:
      - privacyguard-network

networks:
  privacyguard-network:
    driver: bridge