version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
      - python-pii-service
    environment:
      - VITE_API_URL=http://backend:3001
      - VITE_PYTHON_PII_ENDPOINT=http://python-pii-service:8000
    networks:
      - privacyguard-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=http://localhost:8081
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-this-in-production
      - BCRYPT_ROUNDS=12
    networks:
      - privacyguard-network
    # Add depends_on if using database services
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy

  python-pii-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8002:8000"
    networks:
      - privacyguard-network
    # The service needs time to download models on first run
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  privacyguard-network:
    driver: bridge