version: '3.8'

services:
  # Frontend service (React + Vite)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_PYTHON_PII_ENDPOINT=http://python-pii-service:8000
    networks:
      - privacyguard-network

  # Backend service (Node.js + Express) - Development mode
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=http://localhost:5173
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-this-in-production
      - BCRYPT_ROUNDS=12
    networks:
      - privacyguard-network

  # Python PII Detection Service
  python-pii-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    networks:
      - privacyguard-network
    # The service needs time to download models on first run
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  privacyguard-network:
    driver: bridge