// Default permissions for different user roles
export const DEFAULT_PERMISSIONS: Record<string, any[]> = {
  admin: [
    'user:read',
    'user:write',
    'user:delete',
    'dsar:read',
    'dsar:write',
    'risk:read',
    'risk:write',
    'gdpr:read',
    'gdpr:write',
    'policy:read',
    'policy:write',
    'policy:create',
    'policy:update',
    'policy:delete',
    'analytics:read',
  ],
  dpo: [
    'user:read',
    'dsar:read',
    'dsar:write',
    'risk:read',
    'risk:write',
    'gdpr:read',
    'gdpr:write',
    'policy:read',
    'policy:create',
    'policy:update',
    'analytics:read',
  ],
  compliance: [
    'dsar:read',
    'risk:read',
    'gdpr:read',
    'policy:read',
    'analytics:read',
  ],
  legal: [
    'dsar:read',
    'gdpr:read',
    'policy:read',
    'policy:create',
    'policy:update',
  ],
  business: [
    'dsar:read',
    'policy:read',
    'analytics:read',
  ],
  user: [
    'user:read:own',
    'dsar:create:own',
    'dsar:read:own',
  ],
};